# config/defaults.py

"""
Single Source of Truth for all device factory default values.
The keys here MUST match the 'param_name' passed into the UI helpers.
"""

# Fallback SSID when link.auto_credentials is false (default: use AIRTEL_SSID_GEN).
LINK_SSID = "ATUMNAWJ"

LINK_DEFAULTS = {
    "auto_credentials": True,
    "cpe_fallback_ipv4": "10.0.0.1",
    "always_apply_cpe_credentials": True,
    "airtel_gen_path": "",
    "radio_type": "5G",
    "auth_mode": "32",
    "encryption_mode": "8",
    "radio_idx": 1,
    "cpe_radio_idx": 1,
    "bts_serial": "",
    "ssid": "",
    "expected_mode": "linked",
    "min_connected_clients": 1,
    "health_check_timeout_s": 60,
}

DEFAULT_VALUES = {
    # Wireless -> Radio Properties
    "Status": "Enable",
    "Link Type": "PTMP",
    "Radio Mode": "BTS",
    "SSID": LINK_SSID,
    "Bandwidth": "20 MHz",
    "DL/UL Ratio": "Auto",
    "Maximum SUs": "16",
    "DDRS Status": "Enable",
    "Spatial Stream": "Auto",
    "ATPC Status": "Disable",
    "Transmit Power": "1",
    "Maximum EIRP": "0",

    "Syslog IP": "",
    "Temp Log Interval": "30",
    "Location Name": "UBR-Lab",

    # You can expand this as you build out other pages!
    # "IP Address": "192.168.1.1",
    # "Traffic Shaping Status": "Disable",
}

RADIO_24_TEST_VALUES = {
    "SSID_VALID": "UBR_24G_Auto_Test_SSID",
    "SSID_INVALID": "An_Invalid_33_Character_SSID_1234567",
    "KEY_VALID": "Senao24GTestKey!01",
    "KEY_INVALID": "x",
}

RADIO_TEST_VALUES = {
    "SSID_VALID": "A_Valid_32_Character_SSID_123456",
    "SSID_INVALID": "An_Invalid_33_Character_SSID_1234567",
    "MAX_CPE_VALID": "10",
    "MAX_CPE_INVALID": "34",
    "CHANNEL_BTS_VALUES": ["36", "149", "165"],
    "DL_UL_RATIO_VALUES": ["50/50", "80/20"],
    "DDRS_STATUS_VALUES": ["Disable", "Enable"],
    "SPATIAL_STREAM_VALUES": ["Single", "Dual"],
    "MODULATION_INDEX_VALUES": ["MCS12 ( 72 Mbps )", "MCS23 ( 1201 Mbps )"],
    "TRANSMIT_POWER_VALUES": ["1", "26"],
    "TRANSMIT_POWER_INVALID": "27",
    "MAX_EIRP_VALID": "10",
    "MAX_EIRP_INVALID": "101",
    "TREX_BEHAVIOR_DURATION_S": 10,
    "TREX_BEHAVIOR_DL_BW": "200M",
    "TREX_BEHAVIOR_UL_BW": "200M",
}


TRAFFIC_DEFAULTS = {
    "trex": {
        "host": "192.168.3.3",
        "user": "root",
        "password": "ubuntu",
        "directory": "/opt/v3.06",
        "pythonpath": "/opt/v3.06/automation/trex_control_plane/interactive/",
        "client_script": "master_script_extended_16SU.py",  # bundled at traffic/scripts/
        "ports": "0,1",
        "server_cores": 1,
        "server_startup_s": 25,
    }
}


PERFORMANCE_DEFAULTS = {
    "bandwidths": ["HT20", "HT40", "HT80", "HT160"],
    "mcs_rates": [f"MCS{i}" for i in range(24)],
    "ratios": ["80:20", "50:50", "70:30", "75:25"],
    "target_mbps": 800,
    "efficiency_factor": 0.75,
    "use_dynamic_target": True,
    "phy_max_rate_mbps": {},
    "duration_s": 30,
    "radio_index": 1,
    "cpe_radio_index": 1,
    "cpe_su_index": 1,
    "snmp_radio_index": 2,
    "link_wait_s": 45,
    "su_count": 1,
    "spatial_stream": "2",
    "snmp_community": "ubr@rw123",
    "noise_dbm": "-93",
    "packet_size": 1500,
    "profile": "default",
    "recovery_profile": "link_formation",
    "artifact_dir": "reports/artifacts",
    "mcs_traffic_cap_mbps": {
        "MCS0": 80,
        "MCS1": 120,
        "MCS2": 180,
        "MCS3": 260,
        "MCS4": 350,
        "MCS5": 450,
        "MCS6": 550,
        "MCS7": 650,
        "MCS8": 780,
        "MCS9": 900,
        "MCS10": 1050,
        "MCS11": 1200,
    },
}


ATTENUATOR_DEFAULTS = {
    "enabled": False,
    "backend": "auto",  # auto | dll | mock
    "dll_path": "",
    "settle_seconds": 3.0,
    "min_attenuation_db": 0.0,
    "max_attenuation_db": 63.0,
    "su_index": 0,
    "snmp_community": "ubr@rw123",
    "snmp_radio_idx": 2,
    "chains": [
        {"chain": 0, "device_id": None, "serial": None, "lab_brick_id": None, "label": "MIMO chain 0"},
        {"chain": 1, "device_id": None, "serial": None, "lab_brick_id": None, "label": "MIMO chain 1"},
    ],
}

IP_TEST_DEFAULTS = {
    "enabled": False,
    "ipv4_address": "192.168.2.1",
    "ipv4_default_address": "192.168.2.1",
    "ipv4_test_address": "192.168.2.230",
    "ipv4_test_address_alt": "192.168.2.240",
    "ipv4_test_address_alt2": "192.168.2.220",
    "ipv4_test_address_candidates": "192.168.2.230,192.168.2.240,192.168.2.220",
    "ipv4_test_netmask": "255.255.255.0",
    "ipv4_test_gateway": "192.168.2.254",
    "ipv4_netmask": "255.255.255.0",
    "ipv4_gateway": "192.168.2.254",
    "ipv6_prefix_len": 120,
    "ipv6_address": "",
    "ipv6_address_bts": "",
    "ipv6_address_cpe": "",
    "ipv6_gateway": "",
    "ipv6_gateway_bts": "",
    "ipv6_gateway_cpe": "",
    "ipv6_fragmentation_ping_size": 2000,
    "ip19_local_ping_rounds": 3,
    "ip18_apply_wait_s": 40,
    "ip18_apply_ping_interval_s": 3,
    "ip18_configure_cpe": True,
    "ssh_allow_ipv4_fallback": True,
    "ping_count_short": 2,
    "ip_fast_path_enabled": True,
    "ping_count_long": 100,
    "max_ping_loss_pct": 1.0,
    "mtu_test_value": 1400,
    "mtu_restore_value": 1500,
    "gui_settle_seconds": 12,
    "reboot_timeout_s": 200,
    "reboot_max_downtime_s": 200,
    # Minimum time from reboot/reset command before ping/link checks (bench ~180s to RF link).
    "post_reboot_settle_s": 150,
    "post_reset_settle_s": 150,
    "post_reboot_link_timeout_s": 120,
    "post_reboot_ping_wait_s": 90,
    "post_reset_ping_wait_s": 90,
    "network_reload_max_wait_s": 120,
    "reset_retain_command": "",
    "factory_reset_retainip_all": 7,
    "factory_reset_retainip_none": 0,
    "factory_reset_ucidyn_key": "tftp.retip.retainip",
    "factory_reset_script": "/usr/sbin/factory_reset.sh",
    "enable_ip15_factory_restore": True,
    # After IP_15 restore: UCI may look correct but enp3s0.101→BTS ping fails until reboot.
    "ip15_reboot_after_restore": True,
    "post_restore_settle_s": 30,
    # Last resort when mgmt-VLAN ping fails but UCI looks correct (apply/restore bug on bench).
    "enable_reboot_ping_recovery": True,
    "enable_ip_post_case_recovery": True,
    "enable_link_recovery": True,
    "link_recovery_before_precheck": True,
    "link_recovery_after_case": True,
    "link_recovery_timeout_s": 90,
    "link_recovery_poll_s": 3,
    "link_recovery_tx_power": "1",
    "ip15_require_fresh_backup": True,
    "allow_stale_backup_archive": False,
    "backup_via_gui": True,
    "take_session_backup": True,
    "backup_min_bytes": 1024,
    "stop_on_first_failure": True,
    "require_testbed_baseline": True,
    "baseline_network_reload_wait_s": 30,
    "preflight_enabled": True,
    "post_event_recovery_enabled": True,
    "network_reload_wait_s": 30,
    "iface_up_wait_s": 15,
    "iperf_duration_s": 10,
    "iperf_port": 5201,
    "iperf_server_v4": "",
    "iperf_server_v6": "",
    "iperf_expected_tcp_mbps": 50.0,
    "iperf_expected_udp_mbps": 40.0,
    "iperf_expected_mbps_default": 50.0,
    "iperf_min_throughput_ratio": 0.70,
    "iperf_ipv6_min_throughput_ratio": 0.60,
    "cpe_ipv6_verify_retries": 3,
    "cpe_ipv6_verify_interval_s": 8,
    "iperf_udp_bandwidth": "50M",
    "iperf_session_count": 1,
    "iperf_server_ready_wait_s": 30,
    "iperf_client_retries": 2,
    "ip13_iperf_duration_s": 30,
    "ip13_reboot_delay_s": 5,
    "ip13_recovery_iperf_s": 5,
    "iface_up_wait_s": 45,
    "bts_precheck_ping_wait_s": 20,
    "backup_remote_path": "/tmp/ip_test_backup.tar.gz",
    "backup_archive_path": "",
    "firmware_image_path": "",
    "static_route_cidr": "",
    "static_route_gateway": "",
    "static_route_ping_target": "",
    "ipv6_link_local_iface": "eth0",
    "ipv6_link_local_peer": "",
    "fallback_ipv4": "",
    "fallback_ipv6": "",
    "reachability_use_device_fallback": True,
    "ssh_connect_attempts": 3,
    "ssh_connect_retry_interval_s": 15,
    "remote_ping_retries": 5,
    "remote_ping_retry_interval_s": 10,
    "post_reboot_remote_ping_retries": 12,
    "post_reboot_remote_ping_interval_s": 10,
    "post_reload_remote_ping_retries": 8,
    # When false, remote ping/iperf peers use remote_ping_host / dut.remote_ips (not CPE mgmt).
    "use_cpe_peer": False,
    "remote_ping_host": "",
    "verify_lan_bridge": "br-lan",
    "lab_pc_mgmt_ipv4": "192.168.2.10",
    "lab_pc_mgmt_netmask": "255.255.255.0",
    "lab_pc_remote_mgmt_ipv4": "192.168.2.11",
    "require_gui_for_static_ip": True,
    # False when BTS already has default LAN IP (e.g. 192.168.2.1) — verify only, no GUI write.
    "configure_static_ip": False,
    "ip01_apply_wait_s": 40,
    "ip01_apply_ping_interval_s": 3,
    # After ucidyn apply: keep SSH open this long before br-lan check + lab ping (IP_01).
    "ip01_post_reload_wait_s": 40,
    # When false, leave IP_01 applied LAN IP for subsequent suite cases (restore at suite end only).
    "ip01_restore_baseline_after_case": False,
    # Skip heavy preflight when the previous IP case in the session passed.
    "ip_skip_preflight_when_chain_ok": True,
    # Max ceiling for CPE reachability polls; exits as soon as ping succeeds (every ip03_remote_retry_interval_s).
    "ip03_remote_wait_s": 90,
    "ip03_remote_wait_max_s": 90,
    "ip03_remote_retry_interval_s": 5,
    "link_wait_s": 120,
    "ip03_verify_ipv4_address": "192.168.2.1",
    "ip04_gateway": "192.168.2.254",
    "cpe_ipv4_default_address": "",
    "cpe_ipv4_candidates": "192.168.2.231,192.168.2.241,192.168.2.221",
}

TESTBED_DEFAULTS = {
    "enabled": True,
    "bootstrap_on_start": True,
    "configure_vlan_modes": True,
    "strict_ipv6": True,
    "recovery": {
        "bts_fallback_ipv4": "10.0.0.1",
        "bootstrap_fallback_ipv4s": [],
    },
    "bootstrap_fallback_ipv4": "10.0.0.1",
    "bootstrap_fallback_ipv4s": [],
    "factory_defaults": {
        "bts_vlan_mode": "qinq",
        "cpe_vlan_mode": "transparent",
    },
    "qinq": {"svlan": 100, "cvlan": 101},
    "mgmt_vlan": {
        "prefix_len": 120,
        "uci_key": "vlan.ath1.mgmtvlan",
        "uci_value": 101,
        "lab_pc_vlan_id": 101,
        "ipv6_bts": "",
        "ipv6_cpe": "",
        "ipv6_bts_pc": "",
        "ipv6_cpe_pc": "",
        "set_on_cpe": False,
        "bts_apply_commands": [],
        "cpe_apply_commands": [],
    },
    "vlan_uci": {
        "bts_radio": "ath1",
        "cpe_radio": "ath1",
        "bts": {
            "mode_key": "vlan.ath1.mode",
            "mode_value": "qinq",
            "svlan_key": "vlan.ath1.svlan",
            "cvlan_key": "vlan.ath1.cvlan",
            "mgmtvlan_key": "vlan.ath1.mgmtvlan",
        },
        "cpe": {
            "mode_key": "vlan.ath1.mode",
            "mode_value": "transparent",
        },
    },
    "lab_pc_tagging": {
        "bts": {"mode": "qinq", "svlan": 100, "cvlan": 101},
        "cpe": {"mode": "untagged"},
    },
    "primary_pc": {
        "local": True,
        "mgmt_interface": "enp3s0",
        "fallback_ipv4": "10.0.0.10",
        "fallback_prefix_len": 8,
        "internet_ssh": "",
    },
    "secondary_pc": {
        "enabled": True,
        "ssh": "",
        "mgmt_interface": "enp3s0",
        "fallback_ipv4": "10.0.0.11",
        "fallback_prefix_len": 8,
        "cpe_factory_ipv4": "10.0.0.1",
        "use_tagged_mgmt_vlan": True,
        "clear_parent_ipv4": True,
        "parent_relocate_ipv4": "192.168.3.20",
        "parent_relocate_netmask": "255.255.255.0",
        "mgmt_vlan_ipv4": "192.168.2.11",
        "mgmt_vlan_netmask": "255.255.255.0",
    },
    "wifi": {
        "enabled": False,
        "interface": "wlan0",
        "ssid": "",
        "psk": "",
    },
    "vlan_ssh": {
        "bts": {"verify_commands": [], "modes": {}},
        "cpe": {"verify_commands": [], "modes": {}},
    },
    "cpe_discovery": {
        "radio_idx": 2,
        "lease_commands": [],
        "discover_commands": [],
    },
    "link_recovery": {
        "restore_bts": True,
        "restore_cpe": True,
        "bts_archive": "config/BTS.tar.gz",
        "cpe_archive": "config/CPE.tar.gz",
    },
}

CAPTURE_DEFAULTS = {
    "enabled": False,
    "username": "root",
    "password": "senao1234#",
    "tool": "tcpdump",
    "artifact_dir": "reports/artifacts/jumbo_captures",
    "remote_tmp_dir": "/tmp/ubr_jumbo_captures",
}