"""DFS catalog synced to ``Senao UBR P2MP Test Plan_Aug26_Alpha_UBR655.xlsx`` sheet ``DFS``.

Radar injection uses DUT ``radartool -i wifi1 bangradar`` (current channel).
"""

from __future__ import annotations

from typing import Any

DFS_TEST_CASES: list[dict[str, Any]] = [
    {
        "id": "TC_DFS_001",
        "title": "Verify Regulatory Compliance (India)",
        "steps": "Check regulatory domain; reject out-of-India RF config.",
        "expected": "Default regulatory domain is India.",
        "status": "implemented",
        "mode": "regdomain_india",
    },
    {
        "id": "TC_DFS_002",
        "title": "Verify Airtel RF Policy Compliance",
        "steps": "Attempt to select a channel from the Airtel banned list.",
        "expected": "Banned channels cannot be selected.",
        "status": "implemented",
        "mode": "banned_channels",
        "channels": [100, 120, 144],
    },
    {
        "id": "TC_DFS_003",
        "title": "Verify Implementation of Standard DFS Behaviors",
        "steps": "Verify CAC, monitoring, radar, evacuation, NOP, event flags exist.",
        "expected": "Standard DFS behaviors are present on the BTS.",
        "status": "implemented",
        "mode": "dfs_capability",
    },
    {
        "id": "TC_DFS_004",
        "title": "Verify 60-Second CAC Duration",
        "steps": "Configure a DFS channel and measure silent listening before TX.",
        "expected": "CAC lasts about 60 seconds before RF transmission.",
        "status": "implemented",
        "mode": "cac_duration",
        "channel": 52,
    },
    {
        "id": "TC_DFS_005",
        "title": "Verify CAC Expiration Limit (60s Window)",
        "steps": "Complete CAC, delay TX >60s, then start transmission.",
        "expected": "A new 60-second CAC is required after expiry.",
        "status": "implemented",
        "mode": "cac_expiry",
        "channel": 52,
    },
    {
        "id": "TC_DFS_006",
        "title": "Verify CAC Before Initial Use",
        "steps": "Configure a DFS channel and monitor startup before first TX.",
        "expected": "CAC runs before initial transmission on the DFS channel.",
        "status": "implemented",
        "mode": "cac_before_use",
        "channel": 52,
    },
    {
        "id": "TC_DFS_007",
        "title": "Verify CAC After Radar Evacuation",
        "steps": "radartool bangradar; observe switch and CAC on the new DFS channel.",
        "expected": "After switch, a 60s CAC runs on the new DFS channel.",
        "status": "implemented",
        "mode": "radar_then_cac",
        "channel": 52,
        "mutates": True,
    },
    {
        "id": "TC_DFS_008",
        "title": "Verify CAC After NOP(No Operation) Expiry",
        "steps": "Wait 30 minutes for NOP clear, then return to the radar-hit channel.",
        "expected": "Fresh 60s CAC before resume. Plan note: no auto-switchback except reboot.",
        "status": "implemented",
        "mode": "nop_expiry_cac",
        "channel": 52,
        "long": True,
        "mutates": True,
    },
    {
        "id": "TC_DFS_009",
        "title": "Verify Off-Channel CAC Behavior",
        "steps": "Off-channel CAC then immediate switch to pre-cleared backup.",
        "expected": "N/A — off-channel CAC not available.",
        "status": "na",
        "mode": "skip_na",
        "note": "Sheet result: Not Available.",
    },
    {
        "id": "TC_DFS_010",
        "title": "Verify Continuous In-Service Monitoring",
        "steps": "Operate on DFS channel, then radartool bangradar.",
        "expected": "Radar is detected while the radio is in service.",
        "status": "implemented",
        "mode": "radar_inservice",
        "channel": 52,
        "mutates": True,
    },
    {
        "id": "TC_DFS_011",
        "title": "Verify Channel Evacuation Time (200 ms)",
        "steps": "bangradar and measure DUT-side time until the channel is vacated.",
        "expected": "TX on the hit channel stops within 200 ms.",
        "status": "implemented",
        "mode": "evac_time",
        "channel": 52,
        "mutates": True,
        "note": "Lab has no spectrum analyzer; wall-clock from bangradar to channel leave.",
    },
    {
        "id": "TC_DFS_012",
        "title": "Verify Radar-Hit Channel Added to NOL",
        "steps": "bangradar, then read the Non-Occupancy List.",
        "expected": "Hit channel is listed in NOL with a 30-minute timer.",
        "status": "implemented",
        "mode": "nol_add",
        "channel": 52,
        "mutates": True,
    },
    {
        "id": "TC_DFS_013",
        "title": "Verify Post-Radar Channel Selection Algorithm",
        "steps": "bangradar and monitor next operating channel.",
        "expected": "BTS selects a new channel (ACS/DCS).",
        "status": "implemented",
        "mode": "post_radar_select",
        "channel": 52,
        "mutates": True,
    },
    {
        "id": "TC_DFS_014",
        "title": "Verify Non-Occupancy Period (NOP) Strictness",
        "steps": "After NOL entry, force the same channel again.",
        "expected": "BTS refuses the NOL channel during NOP.",
        "status": "implemented",
        "mode": "nop_strict",
        "channel": 52,
        "mutates": True,
    },
    {
        "id": "TC_DFS_015",
        "title": "Verify NOL(Non-Occupancy List) Removal Conditions",
        "steps": "Wait 30 minutes and confirm NOL removal.",
        "expected": "Channel leaves NOL only after 30 minutes.",
        "status": "implemented",
        "mode": "nol_remove",
        "channel": 52,
        "long": True,
        "mutates": True,
    },
    {
        "id": "TC_DFS_016",
        "title": "Verify Airtel UBR Banned Channels (100-144)",
        "steps": "Assign channel 100, 120, or 144.",
        "expected": "Channels 100–144 cannot be selected.",
        "status": "implemented",
        "mode": "banned_channels",
        "channels": [100, 120, 144],
    },
    {
        "id": "TC_DFS_017",
        "title": "Verify 160 MHz Channel Block Constraints",
        "steps": "Set 160 MHz and try a channel outside 36–64.",
        "expected": "160 MHz is restricted to channels 36–64.",
        "status": "implemented",
        "mode": "ht160_block",
        "note": "Plan previously failed: DUT still ran 80 MHz after HT160.",
    },
    {
        "id": "TC_DFS_018",
        "title": "Verify CAC for Channels 52-64",
        "steps": "Set channel 52 and monitor startup.",
        "expected": "60-second CAC before radio-up on 52–64.",
        "status": "implemented",
        "mode": "cac_duration",
        "channel": 52,
    },
    {
        "id": "TC_DFS_019",
        "title": "Verify Bandwidth Downgrade on 160 MHz Radar Hit",
        "steps": "Operate HT160, then bangradar in the DFS portion.",
        "expected": "Bandwidth downgrades 160 → 80 MHz.",
        "status": "implemented",
        "mode": "radar_bw_downgrade",
        "mutates": True,
        "note": "Plan: intermittent; fail if still 160 or never reached 160.",
    },
    {
        "id": "TC_DFS_020",
        "title": "Verify Post-Downgrade Channel Selection",
        "steps": "After 160→80 downgrade, check the new 80 MHz block.",
        "expected": "New block is 36–48 or 149–161.",
        "status": "implemented",
        "mode": "post_downgrade_block",
        "mutates": True,
    },
    {
        "id": "TC_DFS_021",
        "title": "Verify CPE Following BTS (Command Verification)",
        "steps": "bangradar on BTS and check CPE follows channel/BW.",
        "expected": "CPE follows BTS channel/bandwidth after CSA.",
        "status": "implemented",
        "mode": "cpe_follow",
        "channel": 52,
        "mutates": True,
    },
    {
        "id": "TC_DFS_022",
        "title": "Verify RRM 160 MHz Bandwidth Restoration",
        "steps": "After downgrade, wait 30 minutes for RRM restore.",
        "expected": "Plan comment: Airtel did not confirm restore; stays on same BW.",
        "status": "implemented",
        "mode": "rrm_restore",
        "long": True,
        "mutates": True,
    },
    {
        "id": "TC_DFS_023",
        "title": "Verify Avoidance of High Radar/Noise Channels",
        "steps": "bangradar on a DFS channel, then trigger ACS.",
        "expected": "ACS/DCS avoids the radar-hit channel.",
        "status": "implemented",
        "mode": "avoid_radar_channel",
        "channel": 52,
        "mutates": True,
    },
    {
        "id": "TC_DFS_024",
        "title": "Verify DFS Event NMS Reporting",
        "steps": "Trigger radar and check NMS traps.",
        "expected": "NMS receives the DFS event.",
        "status": "na",
        "mode": "skip_na",
        "note": "NMS not on this stand.",
    },
    {
        "id": "TC_DFS_025",
        "title": "Verify Event Payload Contents",
        "steps": "Inspect raw NMS payload after radar/CAC/downgrade.",
        "expected": "Payload has channel, timestamps, CAC/NOP/BW fields.",
        "status": "na",
        "mode": "skip_na",
        "note": "NMS not on this stand.",
    },
    {
        "id": "TC_DFS_026",
        "title": "Verify Event Reason Codes",
        "steps": "Trigger radar and inspect local system logs.",
        "expected": "Logs contain RadarDetected / CAC / NOP reason strings.",
        "status": "implemented",
        "mode": "log_reason_codes",
        "channel": 52,
        "mutates": True,
    },
    {
        "id": "TC_DFS_027",
        "title": "Verify Emitted DFS Event Types",
        "steps": "Full DFS cycle event-type headers.",
        "expected": "N/A on this plan revision.",
        "status": "na",
        "mode": "skip_na",
        "note": "Sheet result: Not Applicable.",
    },
    {
        "id": "TC_DFS_028",
        "title": "Verify ACS Convergence Time (< 3 sec)",
        "steps": "bangradar and measure time until a new stable channel is chosen.",
        "expected": "ACS converges in less than 3 seconds.",
        "status": "implemented",
        "mode": "acs_converge",
        "channel": 52,
        "mutates": True,
    },
]


def all_case_ids() -> list[str]:
    return [c["id"] for c in DFS_TEST_CASES]


def case_by_id(case_id: str) -> dict[str, Any]:
    for case in DFS_TEST_CASES:
        if case["id"] == case_id:
            return case
    raise KeyError(case_id)
