"""Logs catalog synced to ``Senao UBR P2MP Test Plan_Aug26_Alpha_2.xlsx`` sheet ``Logs``.

Regenerate: ``PYTHONPATH=. python3 scripts/sync_logs_catalog.py``

``status``:
  - implemented — DUT-side automation (NMS client validation may still be pending)
  - pending — deferred
  - manual — needs external gear

Destructive modes require ``--allow-logs-destructive``.
NMS-related extract/set cases validate DUT only;
NMS side implementation and validation are pending.
"""

from __future__ import annotations

from typing import Any

LOGS_TEST_CASES: list[dict[str, Any]] = [
    {
        "id": "LOGS_01",
        "title": "Log Extraction \u2013 Valid",
        "steps": "From NMS, fetch logs for BTS",
        "expected": "Log file available at NMS",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dut_log_extract",
        "note": "DUT: collect logread/snlog/session logs via SSH. (NMS side implementation and validation pending)"
    },
    {
        "id": "LOGS_02",
        "title": "Log Extraction \u2013 Invalid BTS ID",
        "steps": "Attempt to fetch logs using wrong BTS ID",
        "expected": "Error logged; no file retrieved",
        "dut": "BTS & CPE",
        "type": "Negative",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dut_log_extract",
        "note": "DUT: collect logread/snlog/session logs via SSH. (NMS side implementation and validation pending)"
    },
    {
        "id": "LOGS_03",
        "title": "Log Extraction \u2013 Network Down",
        "steps": "Disconnect NMS from BTS network",
        "expected": "Log extraction fails; error logged",
        "dut": "BTS & CPE",
        "type": "Negative",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dut_log_extract",
        "note": "DUT: collect logread/snlog/session logs via SSH. (NMS side implementation and validation pending)"
    },
    {
        "id": "LOGS_04",
        "title": "Log Extraction \u2013 Large Log File",
        "steps": "Fetch large BTS log file",
        "expected": "Log file retrieved successfully; performance acceptable",
        "dut": "BTS",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dut_log_extract",
        "note": "DUT: collect logread/snlog/session logs via SSH. (NMS side implementation and validation pending)"
    },
    {
        "id": "LOGS_05",
        "title": "Log Extraction \u2013 Multiple BTS",
        "steps": "Fetch logs for multiple BTS units",
        "expected": "All requested log files available at NMS",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Not Available",
        "status": "implemented",
        "mode": "dut_log_extract",
        "note": "DUT: collect logread/snlog/session logs via SSH. (NMS side implementation and validation pending)"
    },
    {
        "id": "LOGS_06",
        "title": "Persistent Logs \u2013 Reboot BTS 4 times",
        "steps": "Reboot BTS 4 times",
        "expected": "Logs after reboot available; last 3 reboots retained",
        "dut": "BTS",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "persistent_reboot_x4",
        "note": "Destructive: reboot BTS 4x; assert DUT logs still readable after."
    },
    {
        "id": "LOGS_07",
        "title": "Persistent Logs \u2013 Verify Extraction",
        "steps": "After reboots, extract logs from NMS",
        "expected": "Each log file can be extracted successfully",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dut_log_extract",
        "note": "DUT: collect logread/snlog/session logs via SSH. (NMS side implementation and validation pending)"
    },
    {
        "id": "LOGS_08",
        "title": "Persistent Logs \u2013 Storage Limit",
        "steps": "Fill BTS log storage beyond limit",
        "expected": "Old logs overwritten; last 3 reboots retained",
        "dut": "BTS & CPE",
        "type": "Negative",
        "plan_result": "Not Available",
        "status": "implemented",
        "mode": "storage_limit_fill",
        "note": "Destructive: fill log storage briefly; assert logging still works / recovers."
    },
    {
        "id": "LOGS_09",
        "title": "Persistent Logs \u2013 NMS Sync",
        "steps": "Reboot BTS and sync logs to NMS",
        "expected": "Log file should be synced to NMS",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dut_log_extract",
        "note": "DUT: collect logread/snlog/session logs via SSH. (NMS side implementation and validation pending)"
    },
    {
        "id": "LOGS_10",
        "title": "Config Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Disable/Enable the radio status and apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert config log evidence."
    },
    {
        "id": "LOGS_11",
        "title": "Config Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Configure the Bandwidth 20 Mhz to 40 Mhz, 40 Mhz to 80 Mhz and 80 Mhz to 20 Mhz and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert config log evidence."
    },
    {
        "id": "LOGS_12",
        "title": "Config Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Disable/Enable the DDRS status and apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert config log evidence."
    },
    {
        "id": "LOGS_13",
        "title": "Config Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Configure the Spatial Stream Auto/Single/Dual Streams and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert config log evidence."
    },
    {
        "id": "LOGS_14",
        "title": "Config Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Configure the Transmit power and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert config log evidence."
    },
    {
        "id": "LOGS_15",
        "title": "Config Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Set Max data rate in Single stream/Dual stream and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert config log evidence."
    },
    {
        "id": "LOGS_16",
        "title": "Config Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Set Maximum EIRP value and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert config log evidence."
    },
    {
        "id": "LOGS_17",
        "title": "Config Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Disable/Enable the DCS Status and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert config log evidence."
    },
    {
        "id": "LOGS_18",
        "title": "Config Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Set RTX Threshold Percent and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert config log evidence."
    },
    {
        "id": "LOGS_19",
        "title": "Config Logs \u2013 Wireless Configurations \u2013 2.4GHz Radio",
        "steps": "Disable/Enable the radio status and apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio24_config_log",
        "note": "DUT: apply wifi0/2.4GHz UCI change; assert logs evidence."
    },
    {
        "id": "LOGS_20",
        "title": "Config Logs \u2013 Wireless Configurations \u2013 2.4GHz Radio",
        "steps": "Configure the Bandwidth 20 Mhz to 40 Mhz and 40 Mhz to 20 Mhz and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio24_config_log",
        "note": "DUT: apply wifi0/2.4GHz UCI change; assert logs evidence."
    },
    {
        "id": "LOGS_21",
        "title": "Config Logs \u2013 Wireless Configurations \u2013 2.4GHz Radio",
        "steps": "Configure the channel and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio24_config_log",
        "note": "DUT: apply wifi0/2.4GHz UCI change; assert logs evidence."
    },
    {
        "id": "LOGS_22",
        "title": "Config Logs \u2013 Wireless Configurations \u2013 QoS",
        "steps": "Add PIR Entries and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "qos_config_log",
        "note": "DUT: tweak ath1qos UCI; assert logs evidence."
    },
    {
        "id": "LOGS_23",
        "title": "Config Logs \u2013 Wireless Configurations \u2013 QoS",
        "steps": "Add PIR List and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "qos_config_log",
        "note": "DUT: tweak ath1qos UCI; assert logs evidence."
    },
    {
        "id": "LOGS_24",
        "title": "Config Logs \u2013 Wireless Configurations \u2013 QoS",
        "steps": "Set SFC list for DL/UL and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "qos_config_log",
        "note": "DUT: tweak ath1qos UCI; assert logs evidence."
    },
    {
        "id": "LOGS_25",
        "title": "Config Logs \u2013 Network Configurations \u2013 IP Configurations",
        "steps": "Set IPV4 and IPV6 Address and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "ip_config_log",
        "note": "DUT: touch network.lan IPv6 proto."
    },
    {
        "id": "LOGS_26",
        "title": "Config Logs \u2013 Network Configurations \u2013 Vlan Configurations",
        "steps": "Set Mgmt Vlan and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "mgmt_vlan_log",
        "note": "DUT: set mgmtvlan via ucidyn."
    },
    {
        "id": "LOGS_27",
        "title": "Config Logs \u2013 Network Configurations \u2013 Vlan Configurations",
        "steps": "Set Inner and Outer Vlans for Q-in-Q Vlan and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "qinq_vlan_log",
        "note": "DUT: set QinQ svlan/cvlan via ucidyn."
    },
    {
        "id": "LOGS_28",
        "title": "Config Logs \u2013 Network Configurations \u2013 Ethernet Configurations",
        "steps": "Configure the Speed / Dulpex and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "eth_speed_log",
        "note": "DUT: eth speed/duplex status + log."
    },
    {
        "id": "LOGS_29",
        "title": "Config Logs \u2013 Network Configurations \u2013 Ethernet Configurations",
        "steps": "Set MTU till 9000 Byts and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "mtu_config_log",
        "note": "DUT: set network.lan.mtu."
    },
    {
        "id": "LOGS_30",
        "title": "Config Logs \u2013 Network Configurations \u2013 DHCP/Leases Configurations \u2013 Server",
        "steps": "Disable/Enable the DHCP Server and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dhcp_config_log",
        "note": "DUT: tweak dhcp.lan / lan24 / host entry; assert logs evidence."
    },
    {
        "id": "LOGS_31",
        "title": "Config Logs \u2013 Network Configurations \u2013 DHCP/Leases Configurations \u2013 Server",
        "steps": "Set Start IPV4 Address and End IPV4 Address and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dhcp_config_log",
        "note": "DUT: tweak dhcp.lan / lan24 / host entry; assert logs evidence."
    },
    {
        "id": "LOGS_32",
        "title": "Config Logs \u2013 Network Configurations \u2013 DHCP/Leases Configurations \u2013 Server",
        "steps": "Set Lease Time and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dhcp_config_log",
        "note": "DUT: tweak dhcp.lan / lan24 / host entry; assert logs evidence."
    },
    {
        "id": "LOGS_33",
        "title": "Config Logs \u2013 Network Configurations \u2013 DHCP/Leases Configurations \u2013 2.4 GHz Radio",
        "steps": "Set IP Address and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dhcp_config_log",
        "note": "DUT: tweak dhcp.lan / lan24 / host entry; assert logs evidence."
    },
    {
        "id": "LOGS_34",
        "title": "Config Logs \u2013 Network Configurations \u2013 DHCP/Leases Configurations \u2013 2.4 GHz Radio",
        "steps": "Enable/ Disable DHCP Server and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dhcp_config_log",
        "note": "DUT: tweak dhcp.lan / lan24 / host entry; assert logs evidence."
    },
    {
        "id": "LOGS_35",
        "title": "Config Logs \u2013 Network Configurations \u2013 DHCP/Leases Configurations \u2013 2.4 GHz Radio",
        "steps": "Set Start IP Address and End IP Address and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dhcp_config_log",
        "note": "DUT: tweak dhcp.lan / lan24 / host entry; assert logs evidence."
    },
    {
        "id": "LOGS_36",
        "title": "Config Logs \u2013 Network Configurations \u2013 DHCP/Leases Configurations \u2013 2.4 GHz Radio",
        "steps": "Set Lease Time and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dhcp_config_log",
        "note": "DUT: tweak dhcp.lan / lan24 / host entry; assert logs evidence."
    },
    {
        "id": "LOGS_37",
        "title": "Config Logs \u2013 Network Configurations \u2013 DHCP/Leases Configurations \u2013 Fixed Leases",
        "steps": "Add the Lease Devices and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dhcp_config_log",
        "note": "DUT: tweak dhcp.lan / lan24 / host entry; assert logs evidence."
    },
    {
        "id": "LOGS_38",
        "title": "Config Logs \u2013 Mangement Configurations \u2013 System Configurations \u2013 General",
        "steps": "Set Timezone and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "timezone_set_log",
        "note": "DUT: set timezone via ucidyn."
    },
    {
        "id": "LOGS_39",
        "title": "Config Logs \u2013 Mangement Configurations \u2013 System Configurations \u2013 General",
        "steps": "Set NTP Servers and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "ntp_set_log",
        "note": "DUT: set NTP server via ucidyn."
    },
    {
        "id": "LOGS_40",
        "title": "Config Logs \u2013 Mangement Configurations \u2013 System Configurations \u2013 General",
        "steps": "Set NMS Server and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "nms_server_set_dut",
        "note": "DUT: set NMS server UCI via ucidyn. (NMS side implementation and validation pending)"
    },
    {
        "id": "LOGS_41",
        "title": "Config Logs \u2013 Mangement Configurations \u2013 System Configurations \u2013 Logging",
        "steps": "Set Server IP to Save System Logs and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "remote_syslog_set",
        "note": "DUT: set system log_ip/log_port via ucidyn."
    },
    {
        "id": "LOGS_42",
        "title": "Config Logs \u2013 Mangement Configurations \u2013 System Configurations \u2013 Logging",
        "steps": "Disable/Enable the Temerature Loggs and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "temp_log_toggle",
        "note": "DUT: toggle templogstatus via ucidyn."
    },
    {
        "id": "LOGS_43",
        "title": "Config Logs \u2013 Mangement Configurations \u2013 System Configurations \u2013 Logging",
        "steps": "Set time Interval upto 60 Min and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "temp_interval_set",
        "note": "DUT: set temploginterval via ucidyn; verify UCI (no full 30/60m wait)."
    },
    {
        "id": "LOGS_44",
        "title": "Config Logs \u2013 Mangement Configurations \u2013 System Configurations \u2013 Location",
        "steps": "Set BTS ID, Site ID, Email, Phone Number and Distance in km/miles and Apply",
        "expected": "Check the logs are genrated on Config logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "location_set_log",
        "note": "DUT: set location fields via ucidyn."
    },
    {
        "id": "LOGS_45",
        "title": "Config Logs \u2013 Softreboot",
        "steps": "Softreboot the devices",
        "expected": "Check that logs are genrated should be these without any loss of Log data",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "soft_reboot_log",
        "note": "Destructive: soft reboot DUT; assert logs persist / regenerate."
    },
    {
        "id": "LOGS_46",
        "title": "Config Logs \u2013 Hardreboot",
        "steps": "Hardreboot the devices",
        "expected": "Check that logs are genrated should be these without any loss of Log data",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "hard_reboot_log",
        "note": "Destructive: hard-style reboot (sysrq/reboot -f); assert logs after recover."
    },
    {
        "id": "LOGS_47",
        "title": "Device Logs \u2013 Memory",
        "steps": "Make memory used to 80% of the devices",
        "expected": "Check the logs are genrated on Device Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "memory_pressure_log",
        "note": "Destructive: raise mem use ~80%; assert DUT logs still writable."
    },
    {
        "id": "LOGS_48",
        "title": "Device Logs \u2013 Memory",
        "steps": "Make memory used to 95% of the devices",
        "expected": "Check the logs are genrated on Device Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "memory_pressure_log",
        "note": "Destructive: raise mem use ~95%; assert DUT logs still writable."
    },
    {
        "id": "LOGS_49",
        "title": "Device Logs \u2013 Firmware Upgrade",
        "steps": "Upgrade the firmware to latestone",
        "expected": "Check the logs are genrated on Device Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "firmware_upgrade_log",
        "note": "Destructive: sysupgrade if LOGS_FW_IMAGE/profile image set; else skip."
    },
    {
        "id": "LOGS_50",
        "title": "Device Logs \u2013 Softreboot",
        "steps": "Softreboot the devices",
        "expected": "Check the logs are genrated on Device Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "soft_reboot_log",
        "note": "Destructive: soft reboot DUT; assert logs persist / regenerate."
    },
    {
        "id": "LOGS_51",
        "title": "Device Logs \u2013 Hardreboot",
        "steps": "Hardreboot the devices",
        "expected": "Check the logs are genrated on Device Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "hard_reboot_log",
        "note": "Destructive: hard-style reboot (sysrq/reboot -f); assert logs after recover."
    },
    {
        "id": "LOGS_52",
        "title": "Device Logs \u2013 Mangement Configurations \u2013 System Configurations \u2013 Logging",
        "steps": "Set time Interval upto 30 Min and Apply",
        "expected": "Check the logs are genrated in every 30 mins on Temperature Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "temp_interval_set",
        "note": "DUT: set temploginterval via ucidyn; verify UCI (no full 30/60m wait)."
    },
    {
        "id": "LOGS_53",
        "title": "System Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Disable/Enable the radio status and apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert system log evidence."
    },
    {
        "id": "LOGS_54",
        "title": "System Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Configure the Bandwidth 20 Mhz to 40 Mhz, 40 Mhz to 80 Mhz and 80 Mhz to 20 Mhz and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert system log evidence."
    },
    {
        "id": "LOGS_55",
        "title": "System Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Disable/Enable the DDRS status and apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert system log evidence."
    },
    {
        "id": "LOGS_56",
        "title": "System Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Configure the Spatial Stream Auto/Single/Dual Streams and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert system log evidence."
    },
    {
        "id": "LOGS_57",
        "title": "System Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Configure the Transmit power and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert system log evidence."
    },
    {
        "id": "LOGS_58",
        "title": "System Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Set Max data rate in Single stream/Dual stream and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert system log evidence."
    },
    {
        "id": "LOGS_59",
        "title": "System Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Set Maximum EIRP value and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert system log evidence."
    },
    {
        "id": "LOGS_60",
        "title": "System Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Disable/Enable the DCS Status and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert system log evidence."
    },
    {
        "id": "LOGS_61",
        "title": "System Logs \u2013 Wireless Configurations \u2013 Radio",
        "steps": "Set RTX Threshold Percent and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio_config_log",
        "note": "DUT: apply safe radio UCI change; assert system log evidence."
    },
    {
        "id": "LOGS_62",
        "title": "System Logs \u2013 Wireless Configurations \u2013 2.4GHz Radio",
        "steps": "Disable/Enable the radio status and apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio24_config_log",
        "note": "DUT: apply wifi0/2.4GHz UCI change; assert logs evidence."
    },
    {
        "id": "LOGS_63",
        "title": "System Logs \u2013 Wireless Configurations \u2013 2.4GHz Radio",
        "steps": "Configure the Bandwidth 20 Mhz to 40 Mhz and 40 Mhz to 20 Mhz and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio24_config_log",
        "note": "DUT: apply wifi0/2.4GHz UCI change; assert logs evidence."
    },
    {
        "id": "LOGS_64",
        "title": "System Logs \u2013 Wireless Configurations \u2013 2.4GHz Radio",
        "steps": "Configure the channel and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "radio24_config_log",
        "note": "DUT: apply wifi0/2.4GHz UCI change; assert logs evidence."
    },
    {
        "id": "LOGS_65",
        "title": "System Logs \u2013 Wireless Configurations \u2013 QoS",
        "steps": "Add PIR Entries and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "qos_config_log",
        "note": "DUT: tweak ath1qos UCI; assert logs evidence."
    },
    {
        "id": "LOGS_66",
        "title": "System Logs \u2013 Wireless Configurations \u2013 QoS",
        "steps": "Add PIR List and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "qos_config_log",
        "note": "DUT: tweak ath1qos UCI; assert logs evidence."
    },
    {
        "id": "LOGS_67",
        "title": "System Logs \u2013 Wireless Configurations \u2013 QoS",
        "steps": "Set SFC list for DL/UL and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "qos_config_log",
        "note": "DUT: tweak ath1qos UCI; assert logs evidence."
    },
    {
        "id": "LOGS_68",
        "title": "System Logs \u2013 Network Configurations \u2013 IP Configurations",
        "steps": "Set IPV4 and IPV6 Address and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "ip_config_log",
        "note": "DUT: touch network.lan IPv6 proto."
    },
    {
        "id": "LOGS_69",
        "title": "System Logs \u2013 Network Configurations \u2013 Vlan Configurations",
        "steps": "Set Mgmt Vlan and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "mgmt_vlan_log",
        "note": "DUT: set mgmtvlan via ucidyn."
    },
    {
        "id": "LOGS_70",
        "title": "System Logs \u2013 Network Configurations \u2013 Vlan Configurations",
        "steps": "Set Inner and Outer Vlans for Q-in-Q Vlan and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "qinq_vlan_log",
        "note": "DUT: set QinQ svlan/cvlan via ucidyn."
    },
    {
        "id": "LOGS_71",
        "title": "System Logs \u2013 Network Configurations \u2013 Ethernet Configurations",
        "steps": "Configure the Speed / Dulpex and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "eth_speed_log",
        "note": "DUT: eth speed/duplex status + log."
    },
    {
        "id": "LOGS_72",
        "title": "System Logs \u2013 Network Configurations \u2013 Ethernet Configurations",
        "steps": "Set MTU till 9000 Byts and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "mtu_config_log",
        "note": "DUT: set network.lan.mtu."
    },
    {
        "id": "LOGS_73",
        "title": "System Logs \u2013 Network Configurations \u2013 DHCP/Leases Configurations \u2013 Server",
        "steps": "Disable/Enable the DHCP Server and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dhcp_config_log",
        "note": "DUT: tweak dhcp.lan / lan24 / host entry; assert logs evidence."
    },
    {
        "id": "LOGS_74",
        "title": "System Logs \u2013 Network Configurations \u2013 DHCP/Leases Configurations \u2013 Server",
        "steps": "Set Start IPV4 Address and End IPV4 Address and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dhcp_config_log",
        "note": "DUT: tweak dhcp.lan / lan24 / host entry; assert logs evidence."
    },
    {
        "id": "LOGS_75",
        "title": "System Logs \u2013 Network Configurations \u2013 DHCP/Leases Configurations \u2013 Server",
        "steps": "Set Lease Time and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dhcp_config_log",
        "note": "DUT: tweak dhcp.lan / lan24 / host entry; assert logs evidence."
    },
    {
        "id": "LOGS_76",
        "title": "System Logs \u2013 Network Configurations \u2013 DHCP/Leases Configurations \u2013 2.4 GHz Radio",
        "steps": "Set IP Address and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dhcp_config_log",
        "note": "DUT: tweak dhcp.lan / lan24 / host entry; assert logs evidence."
    },
    {
        "id": "LOGS_77",
        "title": "System Logs \u2013 Network Configurations \u2013 DHCP/Leases Configurations \u2013 2.4 GHz Radio",
        "steps": "Enable/ Disable DHCP Server and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dhcp_config_log",
        "note": "DUT: tweak dhcp.lan / lan24 / host entry; assert logs evidence."
    },
    {
        "id": "LOGS_78",
        "title": "System Logs \u2013 Network Configurations \u2013 DHCP/Leases Configurations \u2013 2.4 GHz Radio",
        "steps": "Set Start IP Address and End IP Address and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dhcp_config_log",
        "note": "DUT: tweak dhcp.lan / lan24 / host entry; assert logs evidence."
    },
    {
        "id": "LOGS_79",
        "title": "System Logs \u2013 Network Configurations \u2013 DHCP/Leases Configurations \u2013 2.4 GHz Radio",
        "steps": "Set Lease Time and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dhcp_config_log",
        "note": "DUT: tweak dhcp.lan / lan24 / host entry; assert logs evidence."
    },
    {
        "id": "LOGS_80",
        "title": "System Logs \u2013 Network Configurations \u2013 DHCP/Leases Configurations \u2013 Fixed Leases",
        "steps": "Add the Lease Devices and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "dhcp_config_log",
        "note": "DUT: tweak dhcp.lan / lan24 / host entry; assert logs evidence."
    },
    {
        "id": "LOGS_81",
        "title": "System Logs \u2013 Mangement Configurations \u2013 System Configurations \u2013 General",
        "steps": "Set Timezone and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "timezone_set_log",
        "note": "DUT: set timezone via ucidyn."
    },
    {
        "id": "LOGS_82",
        "title": "System Logs \u2013 Mangement Configurations \u2013 System Configurations \u2013 General",
        "steps": "Set NTP Servers and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "ntp_set_log",
        "note": "DUT: set NTP server via ucidyn."
    },
    {
        "id": "LOGS_83",
        "title": "System Logs \u2013 Mangement Configurations \u2013 System Configurations \u2013 General",
        "steps": "Set NMS Server and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "nms_server_set_dut",
        "note": "DUT: set NMS server UCI via ucidyn. (NMS side implementation and validation pending)"
    },
    {
        "id": "LOGS_84",
        "title": "System Logs \u2013 Mangement Configurations \u2013 System Configurations \u2013 Logging",
        "steps": "Set Server IP to Save System Logs and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "remote_syslog_set",
        "note": "DUT: set system log_ip/log_port via ucidyn."
    },
    {
        "id": "LOGS_85",
        "title": "System Logs \u2013 Mangement Configurations \u2013 System Configurations \u2013 Logging",
        "steps": "Disable/Enable the Temerature Loggs and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "temp_log_toggle",
        "note": "DUT: toggle templogstatus via ucidyn."
    },
    {
        "id": "LOGS_86",
        "title": "System Logs \u2013 Mangement Configurations \u2013 System Configurations \u2013 Logging",
        "steps": "Set time Interval upto 60 Min and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "temp_interval_set",
        "note": "DUT: set temploginterval via ucidyn; verify UCI (no full 30/60m wait)."
    },
    {
        "id": "LOGS_87",
        "title": "System Logs \u2013 Mangement Configurations \u2013 System Configurations \u2013 Location",
        "steps": "Set BTS ID, Site ID, Email, Phone Number and Distance in km/miles and Apply",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "location_set_log",
        "note": "DUT: set location fields via ucidyn."
    },
    {
        "id": "LOGS_88",
        "title": "System Logs \u2013 Softreboot",
        "steps": "Softreboot the devices",
        "expected": "Check that logs are genrated should be these without any loss of Log data",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "soft_reboot_log",
        "note": "Destructive: soft reboot DUT; assert logs persist / regenerate."
    },
    {
        "id": "LOGS_89",
        "title": "System Logs \u2013 Hardreboot",
        "steps": "Hardreboot the devices",
        "expected": "Check that logs are genrated should be these without any loss of Log data",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "hard_reboot_log",
        "note": "Destructive: hard-style reboot (sysrq/reboot -f); assert logs after recover."
    },
    {
        "id": "LOGS_90",
        "title": "System Logs \u2013 Memory",
        "steps": "Make memory used to 80% of the devices",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "memory_pressure_log",
        "note": "Destructive: raise mem use ~80%; assert DUT logs still writable."
    },
    {
        "id": "LOGS_91",
        "title": "System Logs \u2013 Memory",
        "steps": "Make memory used to 95% of the devices",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "memory_pressure_log",
        "note": "Destructive: raise mem use ~95%; assert DUT logs still writable."
    },
    {
        "id": "LOGS_92",
        "title": "System Logs \u2013 Firmware Upgrade",
        "steps": "Upgrade the firmware to latestone",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "firmware_upgrade_log",
        "note": "Destructive: sysupgrade if LOGS_FW_IMAGE/profile image set; else skip."
    },
    {
        "id": "LOGS_93",
        "title": "System Logs \u2013 Softreboot",
        "steps": "Softreboot the devices",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "soft_reboot_log",
        "note": "Destructive: soft reboot DUT; assert logs persist / regenerate."
    },
    {
        "id": "LOGS_94",
        "title": "System Logs \u2013 Hardreboot",
        "steps": "Hardreboot the devices",
        "expected": "Check the logs are genrated on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "hard_reboot_log",
        "note": "Destructive: hard-style reboot (sysrq/reboot -f); assert logs after recover."
    },
    {
        "id": "LOGS_95",
        "title": "System Logs \u2013 Mangement Configurations \u2013 System Configurations \u2013 Logging",
        "steps": "Set time Interval upto 30 Min and Apply",
        "expected": "Check the logs are genrated in every 30 mins on System Logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "temp_interval_set",
        "note": "DUT: set temploginterval via ucidyn; verify UCI (no full 30/60m wait)."
    },
    {
        "id": "LOGS_96",
        "title": "User Logs \u2013 Login Credentials",
        "steps": "Login to device using installer as user name and senao123 as Password",
        "expected": "Check the logs are genrated in user logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "user_login_log",
        "note": "GUI login as installer; assert DUT session/snlog user-log entry."
    },
    {
        "id": "LOGS_97",
        "title": "User Logs \u2013 Login Credentials",
        "steps": "Login to device using admin as user name and admin as Password",
        "expected": "Check the logs are genrated in user logs",
        "dut": "BTS & CPE",
        "type": "Validation",
        "plan_result": "Pass",
        "status": "implemented",
        "mode": "user_login_log",
        "note": "GUI login as admin; assert DUT session/snlog user-log entry."
    }
]


def all_case_ids() -> list[str]:
    return [c["id"] for c in LOGS_TEST_CASES]


def case_by_id(case_id: str) -> dict[str, Any]:
    for case in LOGS_TEST_CASES:
        if case["id"] == case_id:
            return case
    raise KeyError(case_id)


def implemented_case_ids() -> list[str]:
    return [c["id"] for c in LOGS_TEST_CASES if c.get("status") == "implemented"]


DESTRUCTIVE_MODES = frozenset(
    {
        "soft_reboot_log",
        "hard_reboot_log",
        "memory_pressure_log",
        "firmware_upgrade_log",
        "persistent_reboot_x4",
        "storage_limit_fill",
    }
)
