"""QoS catalog synced to ``Senao UBR P2MP Test Plan_Jul23.xlsx`` sheet ``QoS``.

TESTCASE-ID values match the plan exactly (``QoS_01`` … ``QoS_40``).
``status``:
  - implemented — live TRex + queue_stats automation available (or pass-by-default)
  - manual — to be tested manually (not automated)
  - not_available — platform/lab limitation; skipped with Not available badge
  - pending — legacy; prefer ``manual`` for cases left to manual test
"""

from __future__ import annotations

from typing import Any

QOS_TEST_CASES: list[dict[str, Any]] = [
    {
        'id': 'QoS_01',
        'title': 'Validate that QoS ensures voice packets are prioritized while maintaining acceptable performance for data traffic.',
        'steps': '1. Configure QoS to prioritize voice traffic. \n2. Generate voice traffic. \n3. Monitor traffic.',
        'expected': 'Voice traffic is prioritized with minimal latency and jitter. Data traffic experiences no significant delay.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'voice_priority',
        'classes': ['voice', 'bronze', 'best_effort'],
    },
    {
        'id': 'QoS_02',
        'title': 'Confirm video streams are prioritized to guarantee smooth playback, with non‑video traffic handled at lower priority.',
        'steps': '1. Configure QoS to prioritize video streaming. \n2. Stream video content. \n3. Monitor bandwidth allocation.',
        'expected': 'Video traffic receives higher priority, maintaining smooth playback. Other traffic is deprioritized.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'video_priority',
        'classes': ['arvr', 'bronze', 'best_effort'],
        'note': 'Profile1 maps video/streaming to ARVR PIR (queue3).',
    },
    {
        'id': 'QoS_03',
        'title': 'Verify that gaming traffic is prioritized to minimize latency and packet loss for uninterrupted gameplay.',
        'steps': '1. Set QoS policies for gaming traffic. \n2. Initiate gaming session. \n3. Measure latency and packet loss.',
        'expected': 'Gaming traffic has reduced latency and packet loss, ensuring smooth gameplay.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'gaming_priority',
        'classes': ['gold', 'bronze', 'best_effort'],
        'note': 'No dedicated gaming PIR; Gold (DSCP 32/…) is the interactive mid-high class.',
    },
    {
        'id': 'QoS_04',
        'title': 'Validate that QoS policies enforce correct prioritization hierarchy across traffic classes.',
        'steps': '1. Configure multiple traffic priorities simultaneously. \n2. Generate traffic for each priority. \n3. Observe traffic handling.',
        'expected': 'Traffic is prioritized according to QoS settings, with high-priority traffic receiving precedence.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'hierarchy',
        'classes': None,
    },
    {
        'id': 'QoS_05',
        'title': 'Confirm bandwidth caps are applied to low‑priority flows to prevent congestion.',
        'steps': '1. Set maximum bandwidth limits for low-priority traffic. \n2. Generate low-priority traffic. \n3. Monitor bandwidth usage.',
        'expected': 'Low-priority traffic is limited to configured bandwidth, preventing it from congesting the link.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'low_priority_cap',
        'classes': ['control', 'voice', 'bronze'],
        'dl_bw': '150M',
        'ul_bw': '150M',
        'equal_share': False,
    },
    {
        'id': 'QoS_06',
        'title': 'Verify that critical applications receive guaranteed performance under QoS enforcement.',
        'steps': '1. Introduce congestion by generating high traffic load. \n2. Observe QoS behavior during congestion.',
        'expected': 'QoS policies effectively prioritize critical traffic, maintaining performance for high-priority data.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'critical_congestion',
        'classes': ['control', 'bronze', 'best_effort'],
        'dl_bw': '200M',
        'ul_bw': '200M',
        'equal_share': False,
    },
    {
        'id': 'QoS_07',
        'title': 'Establish baseline performance without QoS to compare improvements when enabled.',
        'steps': '1. Disable QoS. \n2. Generate mixed traffic. \n3. Measure latency and throughput.',
        'expected': 'Without QoS, traffic performance is inconsistent, with possible delays and packet loss.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'baseline_mixed',
        'classes': None,
        'equal_share': True,
        'note': 'Baseline records mixed equal-share traffic without priority assertions (QoS still enabled on DUT).',
    },
    {
        'id': 'QoS_08',
        'title': 'Validate DSCP‑based classification accuracy and enforcement across the network.',
        'steps': '1. Enable QoS with different DSCP markings. \n2. Send traffic with varied DSCP values. \n3. Verify traffic classification.',
        'expected': 'Traffic is correctly classified and prioritized based on DSCP markings.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'dscp_classification',
        'classes': None,
    },
    {
        'id': 'QoS_09',
        'title': 'Verify simultaneous prioritization of voice and data traffic without performance loss.',
        'steps': '1. Set up QoS for voice and data traffic. \n2. Generate both simultaneously. \n3. MeaCPEre latency and throughput.',
        'expected': 'Voice traffic remains low latency; data traffic throughput is maintained without degradation.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'voice_and_data',
        'classes': ['voice', 'gold', 'best_effort'],
    },
    {
        'id': 'QoS_10',
        'title': 'Ensure rate limits are consistently applied to prevent bandwidth abuse.',
        'steps': '1. Apply rate limiting to specific traffic types. \n2. Generate traffic exceeding limits. \n3. Observe enforcement.',
        'expected': 'Rate limiting is enforced, preventing traffic from exceeding configured thresholds.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'rate_limit',
        'classes': ['oam', 'best_effort'],
        'dl_bw': '100M',
        'ul_bw': '100M',
        'equal_share': False,
    },
    {
        'id': 'QoS_11',
        'title': 'Confirm scheduling ensures high‑priority traffic is forwarded before lower classes.',
        'steps': '1. Configure QoS with different priority levels. \n2. Send multiple traffic streams. \n3. Observe handling order.',
        'expected': 'Higher priority traffic is transmitted first during contention.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'scheduling_order',
        'classes': ['voice', 'control', 'bronze', 'best_effort'],
        'dl_bw': '150M',
        'ul_bw': '150M',
        'equal_share': False,
    },
    {
        'id': 'QoS_12',
        'title': 'Verify QoS enforcement persists across Customer Premises Equipment under stress.',
        'steps': '1. Monitor QoS performance during link degradation. \n2. Simulate network isCPEes. \n3. MeaCPEre traffic prioritization.',
        'expected': 'QoS maintains prioritization, ensuring critical traffic quality during isCPEes.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'cpe_stress',
        'classes': ['control', 'voice', 'bronze'],
        'dl_bw': '200M',
        'ul_bw': '200M',
    },
    {
        'id': 'QoS_13',
        'title': 'Confirm QoS policies enforce correct allow/deny behavior.',
        'steps': '1. Enable QoS with traffic filtering rules. \n2. Generate allowed and blocked traffic. \n3. Observe filtering effect.',
        'expected': 'Allowed traffic passes; blocked traffic is dropped as per policies.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'allow_deny',
        'classes': ['voice'],
        'note': 'Proxy: only allowed class offered; non-offered queues must stay idle.',
    },
    {
        'id': 'QoS_14',
        'title': 'Ensure QoS differentiates real‑time vs. non‑real‑time traffic correctly.',
        'steps': '1. Configure QoS for real-time applications. \n2. Generate traffic for real-time and non-real-time apps. \n3. Measure delays.',
        'expected': 'Real-time traffic experiences low latency; non-real-time traffic is deprioritized.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'realtime_vs_nonrealtime',
        'classes': ['voice', 'arvr', 'bronze', 'best_effort'],
    },
    {
        'id': 'QoS_15',
        'title': 'Validate logging captures QoS actions for audit and troubleshooting.',
        'steps': '1. Enable logging for QoS events. \n2. Generate various traffic types. \n3. Review logs.',
        'expected': 'Logs accurately record QoS enforcement and classification events.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'qos_logging',
        'classes': ['voice', 'gold', 'bronze'],
        'note': 'Audit artifact = sua queue_stats CSV captured during the run.',
    },
    {
        'id': 'QoS_16',
        'title': 'Confirm dynamic QoS adjustments apply seamlessly without impacting service.',
        'steps': '1. Adjust QoS settings dynamically during operation. \n2. Generate traffic before and after adjustment. \n3. Observe changes.',
        'expected': 'QoS behavior adapts as per new settings without service interruption.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'dynamic_qos',
        'classes': ['voice', 'gold', 'bronze'],
        'note': 'Proxy: consecutive 50M then 150M runs; queues remain classified.',
    },
    {
        'id': 'QoS_17',
        'title': 'Verify QoS handles encrypted traffic streams per configured rules.',
        'steps': '1. Test QoS with different encryption protocols. \n2. Generate encrypted traffic. \n3. Verify classification and prioritization.',
        'expected': 'Encrypted traffic is correctly classified and prioritized based on policies.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'encrypted_traffic',
        'classes': None,
        'note': 'Proxy: DSCP/TOS classification across Profile1 (no real IPsec lab yet).',
    },
    {
        'id': 'QoS_18',
        'title': 'Ensure peer‑to‑peer traffic is controlled to prevent congestion.',
        'steps': '1. Enable QoS for peer-to-peer applications. \n2. Generate P2MP traffic. \n3. Monitor bandwidth and latency.',
        'expected': 'P2MP traffic is managed according to QoS rules, avoiding network congestion.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'p2p_control',
        'classes': ['voice', 'bronze'],
        'dl_bw': '150M',
        'ul_bw': '150M',
        'equal_share': False,
    },
    {
        'id': 'QoS_19',
        'title': 'Validate resilience of QoS prioritization under heavy load.',
        'steps': '1. Test QoS during peak network hours. \n2. Generate high traffic load. \n3. Monitor traffic handling.',
        'expected': 'QoS maintains service quality for high-priority traffic despite congestion.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'heavy_load',
        'classes': None,
        'dl_bw': '200M',
        'ul_bw': '200M',
    },
    {
        'id': 'QoS_20',
        'title': 'Confirm backup flows are deprioritized to preserve critical services.',
        'steps': '1. Configure QoS for backup data transfers. \n2. Initiate large data backups. \n3. Observe impact on other traffic.',
        'expected': 'Backup traffic is scheduled or deprioritized to reduce impact on critical traffic.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'backup_deprioritized',
        'classes': ['control', 'voice', 'bronze'],
        'dl_bw': '150M',
        'ul_bw': '150M',
        'equal_share': False,
    },
    {
        'id': 'QoS_21',
        'title': 'Verify QoS configuration retention across device reboots.',
        'steps': '1. Verify QoS configuration after device reboot. \n2. Generate test traffic. \n3. Confirm policies are retained.',
        'expected': 'QoS settings persist after reboot and function correctly.',
        'dut': 'BTS & CPE',
        'type': 'Negative',
        'status': 'implemented',
        'mode': 'reboot_retention',
        'classes': ['voice', 'bronze', 'best_effort'],
        'note': 'Destructive: snapshot ath1qos → reboot BTS → compare UCI → short traffic verify. Requires --allow-qos-destructive.',
    },
    {
        'id': 'QoS_22',
        'title': 'Validate QoS enforcement across both wired and wireless environments.',
        'steps': '1. Test QoS with mixed wired and wireless clients. \n2. Generate traffic from both. \n3. Monitor performance.',
        'expected': 'QoS applies consistently across wired and wireless clients.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        # Pass by default: P2MP has no wired CPE — wired leg is TRex/PC→BTS; wireless is BTS→CPE (suite).
        'status': 'implemented',
        'mode': 'setup_covered',
        'note': (
            'Pass by default: lab setup already tests wired (TRex/PC→BTS) and wireless '
            '(BTS→CPE SUA queue_stats) on every traffic case; no separate wired CPE exists.'
        ),
    },
    {
        'id': 'QoS_23',
        'title': 'Verify reserved bandwidth is honored and not exceeded.',
        'steps': '1. Implement QoS with bandwidth reservation. \n2. Generate traffic exceeding reservation. \n3. Observe enforcement.',
        'expected': 'Bandwidth reservations are enforced, preventing over-allocation.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'reserved_bandwidth',
        'classes': ['oam', 'gold', 'best_effort'],
        'dl_bw': '100M',
        'ul_bw': '100M',
        'equal_share': False,
    },
    {
        'id': 'QoS_24',
        'title': 'Validate burst traffic is controlled to maintain stable throughput.',
        'steps': '1. Test QoS with different traffic burst sizes. \n2. Generate bursts of traffic.\n3. Monitor handling.',
        'expected': 'Traffic shaping smooths bursts, maintaining consistent performance.',
        'dut': 'BTS & CPE',
        'type': 'Stress',
        'status': 'implemented',
        'mode': 'burst_sizes',
        'classes': ['voice', 'gold', 'bronze'],
        'sizes': [64, 512, 1500],
    },
    {
        'id': 'QoS_25',
        'title': 'Ensure QoS policies scale effectively under different load conditions.',
        'steps': '1. Test QoS with different traffic load scenarios. \n2. Generate low to high traffic volumes. \n3. Monitor performance.',
        'expected': 'QoS maintains service levels across varying traffic loads.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'scale_loads',
        'classes': ['voice', 'gold', 'bronze'],
    },
    {
        'id': 'QoS_26',
        'title': 'Validate mission‑critical apps are prioritized consistently.',
        'steps': '1. Enable QoS for critical infrastructure applications. \n2. Generate traffic. \n3. Measure performance metrics.',
        'expected': 'Critical applications receive high priority, ensuring performance.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'mission_critical',
        'classes': ['control', 'voice', 'best_effort'],
        'dl_bw': '150M',
        'ul_bw': '150M',
        'equal_share': False,
    },
    {
        'id': 'QoS_27',
        'title': 'Confirm monitoring dashboards reflect real‑time QoS enforcement.',
        'steps': '1. Implement QoS with traffic monitoring dashboards. \n2. Generate traffic. \n3. Verify real-time stats.',
        'expected': 'Dashboards accurately display QoS metrics and traffic classification.',
        'dut': 'BTS & CPE',
        'type': 'Validation',
        # Not available: GUI QoS view is queue_stats — already covered by lab cases; no separate dashboard API.
        'status': 'not_available',
        'mode': None,
        'note': 'Not available: GUI dashboard shows sua queue_stats; covered by existing queue_stats validation.',
    },
    {
        'id': 'QoS_28',
        'title': 'Verify QoS resilience under fluctuating wireless signal quality.',
        'steps': '1. Test QoS with different wireless signal qualities. \n2. Generate traffic. \n3. Observe QoS effectiveness.',
        'expected': 'QoS maintains traffic priorities despite varying signal conditions.',
        'dut': 'BTS & CPE',
        'type': 'Negative',
        'status': 'manual',
        'mode': None,
        'note': 'To be tested manually: requires controllable RF attenuation / signal quality steps.',
    },
    {
        'id': 'QoS_29',
        'title': 'Ensure user group‑based QoS policies are enforced correctly.',
        'steps': '1. Configure QoS policies for different user groups. \n2. Generate user traffic. \n3. Verify classification.',
        'expected': 'Traffic from different groups is classified and prioritized accordingly.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        # Not available: Profile1 QoS is SFC/DSCP based, not user-group based.
        'status': 'not_available',
        'mode': None,
        'note': 'Not available: QoS is not user-group specific on this platform (SFC/DSCP Profile1 only).',
    },
    {
        'id': 'QoS_30',
        'title': 'Confirm QoS handles encapsulated traffic streams per policy.',
        'steps': '1. Test QoS with different encryption and encapsulation protocols. \n2. Generate traffic.\n3. Verify classification.',
        'expected': 'Encapsulated traffic is correctly classified and prioritized.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'encapsulated_traffic',
        'classes': None,
        'note': (
            'Lab encapsulation = QinQ (S/C-VLAN) on TRex→BTS plus DSCP/TOS Profile1 mapping '
            '(same path as QoS_17; no separate GRE/IPsec generator).'
        ),
    },
    {
        'id': 'QoS_31',
        'title': 'Verify dynamic bandwidth adjustment under QoS.',
        'steps': '1. Enable QoS with dynamic bandwidth adjustment. \n2. Generate varying traffic loads. \n3. Monitor adjustments.',
        'expected': 'Bandwidth allocation adjusts dynamically based on traffic conditions.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'manual',
        'mode': None,
        'note': 'To be tested manually: DUT dynamic-BW behavior under QoS needs product confirmation.',
    },
    {
        'id': 'QoS_32',
        'title': 'Ensure classification and enforcement match configured QoS rules.',
        'steps': '1. Test QoS with different application types (e.g., HTTP, VoIP, streaming). \n2. Generate traffic. \n3. Verify classification and priority.',
        'expected': 'Traffic is classified accurately, and priorities are enforced as configured.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'dscp_classification',
        'classes': None,
    },
    {
        'id': 'QoS_33',
        'title': 'Validate multi‑device QoS enforcement consistency.',
        'steps': '1. Enable QoS on multiple devices simultaneously. \n2. Generate traffic from all devices. \n3. Observe network behavior.',
        'expected': 'QoS policies are enforced consistently across all devices.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'manual',
        'mode': None,
        'note': 'To be tested manually: requires ≥2 SUs associated with parallel traffic.',
    },
    {
        'id': 'QoS_34',
        'title': 'Confirm policy‑based prioritization accuracy.',
        'steps': '1. Configure QoS with custom policies. \n2. Generate traffic matching and not matching policies. \n3. Verify enforcement.',
        'expected': 'Traffic matching policies is prioritized; non-matching traffic is handled normally.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'policy_priority',
        'classes': ['voice', 'arvr', 'bronze'],
    },
    {
        'id': 'QoS_35',
        'title': 'Verify QoS stability across firmware upgrades.',
        'steps': '1. Test QoS during firmware upgrade. \n2. Generate traffic before and after. \n3. Observe stability.',
        'expected': 'QoS functions correctly during and after firmware updates.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'manual',
        'mode': None,
        'note': 'To be tested manually: firmware upgrade + post-upgrade QoS retention/traffic.',
    },
    {
        'id': 'QoS_36',
        'title': 'Ensure alerts are generated for violations to support monitoring.',
        'steps': '1. Enable logging and alerting for QoS violations. \n2. Generate traffic exceeding limits. \n3. Verify alerts.',
        'expected': 'Alerts are triggered for QoS violations, aiding troubleshooting.',
        'dut': 'BTS & CPE',
        'type': 'Negative',
        # Not available: QoS violation alerts are not implemented on the DUT yet.
        'status': 'not_available',
        'mode': None,
        'note': 'Not available: QoS violation alerts are not yet implemented on the platform.',
    },
    {
        'id': 'QoS_37',
        'title': 'Validate QoS effectiveness across different packet sizes.',
        'steps': '1. Test QoS with different packet sizes. \n2. Generate small and large packets. \n3. Observe handling.',
        'expected': 'QoS handles varying packet sizes efficiently, maintaining performance.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'packet_sizes',
        'classes': ['voice', 'gold', 'bronze'],
        'sizes': [64, 512, 1500],
    },
    {
        'id': 'QoS_38',
        'title': 'Confirm AR/VR and new app traffic is prioritized correctly.',
        'steps': '1. Configure QoS for emerging applications (e.g., AR/VR). \n2. Generate traffic. \n3. Measure latency and throughput.',
        'expected': 'QoS supports emerging application traffic with acceptable performance.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        'status': 'implemented',
        'mode': 'arvr_priority',
        'classes': ['arvr', 'bronze', 'best_effort'],
    },
    {
        'id': 'QoS_39',
        'title': 'Verify QoS enforcement consistency across multiple interfaces.',
        'steps': '1. Verify QoS configuration via GUI. \n2. Generate traffic. \n3. Confirm policies are applied.',
        'expected': 'Policies are consistent and correctly applied across interfaces.',
        'dut': 'BTS & CPE',
        'type': 'Functional',
        # Not available: lab DUT exposes a single QoS-relevant air interface for this suite.
        'status': 'not_available',
        'mode': None,
        'note': 'Not available: only one QoS-relevant interface is available in this lab setup.',
    },
    {
        'id': 'QoS_40',
        'title': 'Validate QoS performance metrics are consistent under high load.',
        'steps': '1. Document QoS performance metrics during high load. \n2. Generate traffic.\n 3. Review logs and stats.',
        'expected': 'QoS maintains expected performance levels under load, with documented metrics.',
        'dut': 'BTS & CPE',
        'type': 'Stress',
        'status': 'implemented',
        'mode': 'metrics_high_load',
        'classes': None,
        'dl_bw': '200M',
        'ul_bw': '200M',
    },
]


def case_by_id(case_id: str) -> dict[str, Any]:
    key = case_id.strip()
    for case in QOS_TEST_CASES:
        if case["id"] == key:
            return case
    raise KeyError(f"Unknown QoS case id: {case_id}")


def all_case_ids() -> list[str]:
    return [c["id"] for c in QOS_TEST_CASES]


def implemented_case_ids() -> list[str]:
    return [c["id"] for c in QOS_TEST_CASES if c.get("status") == "implemented"]


def runnable_case_ids() -> list[str]:
    """Cases that execute lab traffic; excludes manual / not_available."""
    return [c["id"] for c in QOS_TEST_CASES if c.get("status") == "implemented"]


def manual_case_ids() -> list[str]:
    return [c["id"] for c in QOS_TEST_CASES if c.get("status") == "manual"]
