"""User Management catalog — Senao UBR P2MP Test Plan sheet User Mgmt (UM_01–UM_50).

``status``:
  - implemented — Playwright role/login/permission automation available
  - pending — catalogued; not automated yet (Phase 2/3)
  - destructive — needs ``--allow-um-destructive`` (reboot / fw / factory / timeout / dual)
"""

from __future__ import annotations

from typing import Any

# role: admin | user | installer | admin_factory (factory default admin/admin for UM_01)
UM_TEST_CASES: list[dict[str, Any]] = [
    {
        "id": "UM_01",
        "title": "Admin login with default password",
        "steps": "Enter username admin and password admin1234",
        "expected": "Login successful, full access granted",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "login_ok",
        "role": "admin",
        "expect_landing": "full",
        "note": "Lab default admin password is admin1234 (not factory admin/admin).",
    },
    {
        "id": "UM_02",
        "title": "User login with default password",
        "steps": "Enter username user and password senao",
        "expected": "Login successful, read-only access",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "login_ok",
        "role": "user",
        "expect_landing": "readonly",
    },
    {
        "id": "UM_03",
        "title": "Installer login with default password",
        "steps": "Enter username installer and password senao123",
        "expected": "Login successful, Quick Start tab only",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "login_ok",
        "role": "installer",
        "expect_landing": "quickstart",
    },
    {
        "id": "UM_04",
        "title": "Admin changes User password",
        "steps": "Login as Admin → Navigate to password settings → Change User password",
        "expected": "Password updated successfully",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "admin_change_user_password",
        "role": "admin",
        "note": "Management → Services → Passwords; mutate only if UM_PERFORM_USER_PASSWORD_CHANGE=1",
    },
    {
        "id": "UM_05",
        "title": "User attempts to change password",
        "steps": "Login as User → Navigate to password settings",
        "expected": "Option not available, action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "user",
        "action": "password_settings",
    },
    {
        "id": "UM_06",
        "title": "Installer attempts to change password",
        "steps": "Login as Installer → Navigate to password settings",
        "expected": "Option not available, action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "installer",
        "action": "password_settings",
    },
    {
        "id": "UM_07",
        "title": "Admin modifies wireless configuration",
        "steps": "Login as Admin → Change SSID → Save",
        "expected": "Configuration updated successfully",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_allowed",
        "role": "admin",
        "action": "ssid_edit",
        "note": "Phase 2: change SSID and restore",
    },
    {
        "id": "UM_08",
        "title": "User attempts to modify SSID",
        "steps": "Login as User → Try editing SSID",
        "expected": "Edit blocked, read-only enforced",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "user",
        "action": "ssid_edit",
    },
    {
        "id": "UM_09",
        "title": "Installer modifies Quick Start IP",
        "steps": "Login as Installer → Change IP address → Save",
        "expected": "IP updated successfully",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_allowed",
        "role": "installer",
        "action": "quickstart_ip",
        "note": "Phase 2: mutate + restore mgmt IP carefully",
    },
    {
        "id": "UM_10",
        "title": "Admin initiates reboot",
        "steps": "Login as Admin → Click reboot",
        "expected": "Device reboots",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "destructive",
        "mode": "action_allowed",
        "role": "admin",
        "action": "reboot",
        "note": "Phase 3: requires --allow-um-destructive",
    },
    {
        "id": "UM_11",
        "title": "User attempts reboot",
        "steps": "Login as User → Click reboot",
        "expected": "Action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "user",
        "action": "reboot",
    },
    {
        "id": "UM_12",
        "title": "Installer attempts reboot",
        "steps": "Login as Installer → Click reboot",
        "expected": "Action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "installer",
        "action": "reboot",
        "note": "Plan expected deny; sheet notes installer still sees reboot (defect)",
    },
    {
        "id": "UM_13",
        "title": "Admin upgrades firmware",
        "steps": "Login as Admin → Upload firmware → Apply",
        "expected": "Firmware upgrade successful",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "destructive",
        "mode": "action_allowed",
        "role": "admin",
        "action": "firmware",
        "note": "Phase 3: needs firmware image + --allow-um-destructive",
    },
    {
        "id": "UM_14",
        "title": "User attempts firmware upgrade",
        "steps": "Login as User → Upload firmware",
        "expected": "Action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "user",
        "action": "firmware",
    },
    {
        "id": "UM_15",
        "title": "Installer attempts firmware upgrade",
        "steps": "Login as Installer → Upload firmware",
        "expected": "Action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "installer",
        "action": "firmware",
        "note": "Plan expected deny; sheet notes installer still sees firmware (defect)",
    },
    {
        "id": "UM_16",
        "title": "Admin downloads configuration file",
        "steps": "Login as Admin → Download config",
        "expected": "File downloaded successfully",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_allowed",
        "role": "admin",
        "action": "config_download",
        "note": "Phase 2",
    },
    {
        "id": "UM_17",
        "title": "User attempts config download",
        "steps": "Login as User → Download config",
        "expected": "Action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "user",
        "action": "config_download",
    },
    {
        "id": "UM_18",
        "title": "Installer attempts config download",
        "steps": "Login as Installer → Download config",
        "expected": "Action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "installer",
        "action": "config_download",
    },
    {
        "id": "UM_19",
        "title": "Admin initiates factory reset",
        "steps": "Login as Admin → Factory reset",
        "expected": "Device reset successfully",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "destructive",
        "mode": "action_allowed",
        "role": "admin",
        "action": "factory_reset",
        "note": "Phase 3: requires --allow-um-destructive",
    },
    {
        "id": "UM_20",
        "title": "User attempts factory reset",
        "steps": "Login as User → Factory reset",
        "expected": "Action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "user",
        "action": "factory_reset",
    },
    {
        "id": "UM_21",
        "title": "Installer attempts factory reset",
        "steps": "Login as Installer → Factory reset",
        "expected": "Action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "installer",
        "action": "factory_reset",
    },
    {
        "id": "UM_22",
        "title": "Admin runs link test tool",
        "steps": "Login as Admin → Run link test",
        "expected": "Tool executes successfully",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_allowed",
        "role": "admin",
        "action": "link_test",
        "note": "Phase 2",
    },
    {
        "id": "UM_23",
        "title": "User attempts link test",
        "steps": "Login as User → Run link test",
        "expected": "Action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "user",
        "action": "link_test",
    },
    {
        "id": "UM_24",
        "title": "Installer attempts link test",
        "steps": "Login as Installer → Run link test",
        "expected": "Action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "installer",
        "action": "link_test",
    },
    {
        "id": "UM_25",
        "title": "Admin views logs",
        "steps": "Login as Admin → Navigate to logs",
        "expected": "Logs displayed",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_allowed",
        "role": "admin",
        "action": "view_logs",
    },
    {
        "id": "UM_26",
        "title": "User views logs",
        "steps": "Login as User → Navigate to logs",
        "expected": "Logs displayed",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_allowed",
        "role": "user",
        "action": "view_logs",
    },
    {
        "id": "UM_27",
        "title": "Installer views logs",
        "steps": "Login as Installer → Navigate to logs",
        "expected": "Logs displayed",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_allowed",
        "role": "installer",
        "action": "view_logs",
        "note": "Plan expected logs; sheet notes installer cannot see logs (defect)",
    },
    {
        "id": "UM_28",
        "title": "Admin runs diagnostics (Ping/Traceroute)",
        "steps": "Login as Admin → Run Ping",
        "expected": "Ping executes successfully",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_allowed",
        "role": "admin",
        "action": "ping",
    },
    {
        "id": "UM_29",
        "title": "User runs diagnostics (Ping/Traceroute)",
        "steps": "Login as User → Run Ping",
        "expected": "Ping executes successfully",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_allowed",
        "role": "user",
        "action": "ping",
    },
    {
        "id": "UM_30",
        "title": "Installer runs diagnostics (Ping/Traceroute)",
        "steps": "Login as Installer → Run Ping",
        "expected": "Ping executes successfully",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_allowed",
        "role": "installer",
        "action": "ping",
        "note": "Plan expected ping; sheet notes installer cannot ping (defect)",
    },
    {
        "id": "UM_31",
        "title": "Admin login with wrong password",
        "steps": "Enter username admin and incorrect password",
        "expected": "Login denied, error message displayed",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "login_deny",
        "role": "admin",
    },
    {
        "id": "UM_32",
        "title": "User login with wrong password",
        "steps": "Enter username user and incorrect password",
        "expected": "Login denied, error message displayed",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "login_deny",
        "role": "user",
    },
    {
        "id": "UM_33",
        "title": "Installer login with wrong password",
        "steps": "Enter username installer and incorrect password",
        "expected": "Login denied, error message displayed",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "login_deny",
        "role": "installer",
    },
    {
        "id": "UM_34",
        "title": "Admin session timeout",
        "steps": "Login as Admin → Stay idle beyond timeout",
        "expected": "Session expires, re-login required",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "destructive",
        "mode": "session_timeout",
        "role": "admin",
        "note": "Phase 3: idle 5 min on Wireless→Radio 1 (no XHR keepalive); UM_SESSION_TIMEOUT_S default 300",
    },
    {
        "id": "UM_35",
        "title": "User session timeout",
        "steps": "Login as User → Stay idle beyond timeout",
        "expected": "Session expires, re-login required",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "destructive",
        "mode": "session_timeout",
        "role": "user",
        "note": "Phase 3: idle 5 min on Wireless→Radio 1 (no XHR keepalive); UM_SESSION_TIMEOUT_S default 300",
    },
    {
        "id": "UM_36",
        "title": "Installer session timeout",
        "steps": "Login as Installer → Stay idle beyond timeout",
        "expected": "Session expires, re-login required",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "destructive",
        "mode": "session_timeout",
        "role": "installer",
        "note": "Phase 3: idle 5 min on Wireless→Radio 1 if reachable; UM_SESSION_TIMEOUT_S default 300",
    },
    {
        "id": "UM_37",
        "title": "Admin attempts simultaneous login",
        "steps": "Login as Admin on two browsers",
        "expected": "Both sessions allowed, tracked in logs",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "dual_login",
        "role": "admin",
        "note": "Phase 3: dual Playwright contexts",
    },
    {
        "id": "UM_38",
        "title": "User attempts simultaneous login",
        "steps": "Login as User on two browsers",
        "expected": "Both sessions allowed, tracked in logs",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "dual_login",
        "role": "user",
        "note": "Phase 3",
    },
    {
        "id": "UM_39",
        "title": "Installer attempts simultaneous login",
        "steps": "Login as Installer on two browsers",
        "expected": "Both sessions allowed, tracked in logs",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "dual_login",
        "role": "installer",
        "note": "Phase 3",
    },
    {
        "id": "UM_40",
        "title": "Admin disconnects wireless link",
        "steps": "Login as Admin → Disconnect wireless link",
        "expected": "Link disconnected successfully",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "destructive",
        "mode": "action_allowed",
        "role": "admin",
        "action": "wireless_disconnect",
        "note": "Phase 3: needs link recovery",
    },
    {
        "id": "UM_41",
        "title": "User attempts disconnect wireless link",
        "steps": "Login as User → Disconnect wireless link",
        "expected": "Action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "user",
        "action": "wireless_disconnect",
    },
    {
        "id": "UM_42",
        "title": "Installer attempts disconnect wireless link",
        "steps": "Login as Installer → Disconnect wireless link",
        "expected": "Action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "installer",
        "action": "wireless_disconnect",
    },
    {
        "id": "UM_43",
        "title": "Admin changes encryption type",
        "steps": "Login as Admin → Change AES-256 to WPA2 → Save",
        "expected": "Encryption updated successfully",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_allowed",
        "role": "admin",
        "action": "encryption_edit",
        "note": "Phase 2: mutate + restore",
    },
    {
        "id": "UM_44",
        "title": "User attempts encryption change",
        "steps": "Login as User → Change encryption",
        "expected": "Action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "user",
        "action": "encryption_edit",
    },
    {
        "id": "UM_45",
        "title": "Installer attempts encryption change",
        "steps": "Login as Installer → Change encryption",
        "expected": "Action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "installer",
        "action": "encryption_edit",
    },
    {
        "id": "UM_46",
        "title": "Admin modifies VLAN ID",
        "steps": "Login as Admin → Change VLAN ID → Save",
        "expected": "VLAN updated successfully",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_allowed",
        "role": "admin",
        "action": "vlan_edit",
        "note": "Phase 2: mutate + restore",
    },
    {
        "id": "UM_47",
        "title": "User attempts VLAN modification",
        "steps": "Login as User → Change VLAN ID",
        "expected": "Action denied",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_denied",
        "role": "user",
        "action": "vlan_edit",
    },
    {
        "id": "UM_48",
        "title": "Installer modifies VLAN ID",
        "steps": "Login as Installer → Change VLAN ID → Save",
        "expected": "VLAN updated successfully",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_allowed",
        "role": "installer",
        "action": "vlan_edit",
        "note": "Phase 2",
    },
    {
        "id": "UM_49",
        "title": "Admin views site survey",
        "steps": "Login as Admin → Navigate to Site Survey",
        "expected": "Survey results displayed",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_allowed",
        "role": "admin",
        "action": "site_survey",
        "note": "Phase 2",
    },
    {
        "id": "UM_50",
        "title": "Installer views site survey",
        "steps": "Login as Installer → Navigate to Site Survey",
        "expected": "Survey results displayed",
        "dut": "BTS & CPE",
        "type": "Functional",
        "status": "implemented",
        "mode": "action_allowed",
        "role": "installer",
        "action": "site_survey",
        "note": "Phase 2",
    },
]


def case_by_id(case_id: str) -> dict[str, Any]:
    key = case_id.strip()
    for case in UM_TEST_CASES:
        if case["id"] == key:
            return case
    raise KeyError(f"Unknown UM case id: {case_id}")


def all_case_ids() -> list[str]:
    return [c["id"] for c in UM_TEST_CASES]


def implemented_case_ids() -> list[str]:
    return [c["id"] for c in UM_TEST_CASES if c.get("status") == "implemented"]
